Task 2
js-tasks-ru/jsbasic-20220901_shvets555 pull request #3
Opened 2022-09-10 15:30 UTC by Sergei-Shvets

2022-09-10 15:31 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-11 10:09 UTC, SinimaWath requested changes

2022-09-11 10:09 UTC, SinimaWath commented on 2-module/1-task/index.js
> +      if (number > 0 && number < Infinity)
Странная проверка, давай лучше используем проверка isFinite

2022-09-11 10:09 UTC, SinimaWath commented on 2-module/2-task/index.js
> +  return (Object.keys(obj).length === 0) ? true : false;
`return Object.keys(obj).length === 0`

2022-09-11 10:25 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-12 19:07 UTC, SinimaWath approved these changes

2022-09-12 19:07 UTC, merged